/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List listings, newest first */
        get: operations["listListings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one listing */
        get: operations["getListing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictions/listing/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get or calculate the price prediction for a listing
         * @description Returns the stored prediction if one exists, ignoring the query parameters. Otherwise calculates, stores and returns a new one.
         */
        get: operations["getPrediction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictions/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculate predictions for several listings
         * @description Unknown listing ids and per-listing failures are skipped, so `count` can be lower than the number of ids sent.
         */
        post: operations["batchPredictions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Listing: {
            /** Format: uuid */
            id: string;
            rentcastId: string;
            address: string;
            city: string;
            state: string;
            zipCode: string;
            latitude: number;
            longitude: number;
            listPrice: number;
            beds: number | null;
            baths: number | null;
            sqft: number | null;
            propertyType: string | null;
            yearBuilt: number | null;
            listingStatus: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ListingsPage: {
            data: components["schemas"]["Listing"][];
            pagination: {
                page: number;
                limit: number;
                /** @description Listings matching the filters across all pages. */
                total: number;
            };
        };
        Error: {
            error: {
                status: number;
                message: string;
                /** @description Only when NODE_ENV=development. */
                details?: unknown;
            };
        };
        PredictionFactors: {
            interestRate: number;
            comps: {
                /** Format: uuid */
                id: string;
                price: number;
                /** @description Miles from the listing. */
                distance: number;
                similarity: number;
            }[];
            marketTrend: number;
            seasonalAdjustment: number;
            pricePerSqft: number;
        } | null;
        Prediction: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            listingId: string;
            predictedPrice: number;
            confidence: number;
            factors: components["schemas"]["PredictionFactors"];
            interestRate: number | null;
            estimatedDelisting: boolean | null;
            delistingReason: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        BatchPredictionResponse: {
            predictions: components["schemas"]["Prediction"][];
            count: number;
        };
        BatchPredictionRequest: {
            listingIds: string[];
            /** @default 6.8 */
            interestRate: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
        };
    };
    listListings: {
        parameters: {
            query?: {
                city?: string;
                state?: string;
                zipCode?: string;
                minPrice?: number | null;
                maxPrice?: number | null;
                beds?: number | null;
                baths?: number | null;
                propertyType?: string;
                lat?: number | null;
                lng?: number | null;
                radiusMiles?: number;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of listings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingsPage"];
                };
            };
            /** @description Invalid path parameter, query parameter or body. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The listing. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
            /** @description Invalid path parameter, query parameter or body. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No listing with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getPrediction: {
        parameters: {
            query?: {
                interestRate?: number;
                marketTrend?: number | null;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The prediction. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Prediction"];
                };
            };
            /** @description Invalid path parameter, query parameter or body. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No listing with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    batchPredictions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["BatchPredictionRequest"];
            };
        };
        responses: {
            /** @description The predictions that succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchPredictionResponse"];
                };
            };
            /** @description Invalid path parameter, query parameter or body. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
